In [4]:
import pandas as pd

In [5]:
info = {
    "Name" : ["Rahul", "Harshita", "Shraddha"],
    "CGPA" : [9.5, 9.0, 8.5]
}
df = pd.DataFrame(info)
print(df)

       Name  CGPA
0     Rahul   9.5
1  Harshita   9.0
2  Shraddha   8.5

In [6]:
df

       Name  CGPA
0     Rahul   9.5
1  Harshita   9.0
2  Shraddha   8.5

In [12]:
# series
s = pd.Series([1, 2, 3, 4, 5])
print(s)
print(type(s))

#index
print(s[0])
print(s[1])

#label
s = pd.Series([23, 24, 25, 26], index = ["Adam", "Eve", "bob", "Charlie"])
print(s, type(s))
print(s.index)

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>
1
2
Adam       23
Eve        24
bob        25
Charlie    26
dtype: int64 <class 'pandas.Series'>
Index(['Adam', 'Eve', 'bob', 'Charlie'], dtype='str')

In [16]:
# Properties of series

#Vectorized operations are allowed
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([10,20,30,40,50])
print(s1 + s2)
s1[0] = 25
changed_s1 = s1.drop(0)
print(s1)
print(changed_s1)

0    11
1    22
2    33
3    44
4    55
dtype: int64
0    25
1     2
2     3
3     4
4     5
dtype: int64
1    2
2    3
3    4
4    5
dtype: int64

In [21]:
# DataFrame (Dictionary of lists)
info = {
    "Name" : ["Rahul", "Harshita", "Shraddha"],
    "CGPA" : [9.5, 9.0, 8.5],
    "Age" : [20, 21, 19]
}
df = pd.DataFrame(info)
print(df, type(df))
print(df.index)
print(df.columns)

       Name  CGPA  Age
0     Rahul   9.5   20
1  Harshita   9.0   21
2  Shraddha   8.5   19 <class 'pandas.DataFrame'>
RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'CGPA', 'Age'], dtype='str')

In [19]:
df

       Name  CGPA  Age
0     Rahul   9.5   20
1  Harshita   9.0   21
2  Shraddha   8.5   19

In [24]:
# List os Lists
df = pd.DataFrame([["Adam", 23], ["Shruti", 21], ["Lucky", 21]], columns = ["Name", "Age"])
print(df, type(df))

     Name  Age
0    Adam   23
1  Shruti   21
2   Lucky   21 <class 'pandas.DataFrame'>

In [23]:
df

        0   1
0    Adam  23
1  Shruti  21
2   Lucky  21

In [25]:
# np array
import numpy as np
np_arr = np.array([[1,2,3], [4,5,6]])
df = pd.DataFrame(np_arr, columns = ["A", "B", "C"]) 
print(df, type(df))

   A  B  C
0  1  2  3
1  4  5  6 <class 'pandas.DataFrame'>

In [5]:
# csv data
import pandas as pd
df = pd.read_csv("employee_data.csv")

print(df, type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.DataFrame'>

In [12]:
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [16]:
# DataFrames
df.head() # starting 5 rows

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000

In [17]:
df.tail(2) # last two rows

   ID   Name  Age Department  Salary
8   9    Ian   35         IT   75000
9  10  Julia   30    Finance   60000

In [18]:
df.sample() # for a random row

   ID   Name  Age Department  Salary
9  10  Julia   30    Finance   60000

In [19]:
df.info() # summary of data

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     str
 2   Age         10 non-null     int64
 3   Department  10 non-null     str
 4   Salary      10 non-null     int64
dtypes: int64(3), str(2)
memory usage: 628.0 bytes

In [22]:
df.shape # returns tuple of rows and cols

(10, 5)

In [23]:
df.describe()

             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  32.900000  64500.000000
std     3.02765   6.674162  15182.226451
min     1.00000  25.000000  47000.000000
25%     3.25000  28.250000  51250.000000
50%     5.50000  31.000000  62500.000000
75%     7.75000  37.250000  74250.000000
max    10.00000  45.000000  91000.000000

In [25]:
df.columns

Index(['ID', 'Name', 'Age', 'Department', 'Salary'], dtype='str')

In [26]:
df.nunique()

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

In [27]:
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [30]:
# AQI data set
df = pd.read_csv("globalAirQuality.csv")
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [32]:
# selecting columns
df["city"]
df[["city", "aqi"]]

           city  aqi
0      New York  108
1      New York   90
2      New York   84
3      New York  158
4      New York   97
...         ...  ...
17995    Zurich  103
17996    Zurich  105
17997    Zurich  122
17998    Zurich   95
17999    Zurich   88

[18000 rows x 2 columns]

In [35]:
# Selecting rows (label/ use loc)
df.loc[0]
df.loc[0:2] # start idx : end index({included)

# (index/ use iloc)
df.iloc[0]
df.iloc[0:2]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969

In [50]:
# cells - row, col
df.loc[0:2, "city"]
df.columns

#df.iloc[0:3, 2]
df.loc[0:2, ["country", "city", "latitude", "longitude"]]
df.iloc[0:3, 1:5]

  country      city  latitude  longitude
0      US  New York    40.713    -74.006
1      US  New York    40.713    -74.006
2      US  New York    40.713    -74.006

In [51]:
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [53]:
#cell
df.at[0, "city"]
df.iat[0, 2]

'New York'